CREATE DATABASE TAO

CREATE TABLE KHACHANG (
    MAKH INT IDENTITY(100,5) NOT NULL PRIMARY KEY,
    TENKH VARCHAR (50) NOT NULL, 
    DIACHI VARCHAR (255),
    SDT VARCHAR (10) CHECK (SDT LIKE '[0,9][0,9][0,9][0,9][0,9][0,9][0,9][0,9][0,9][0,9]')
);

ALTER TABLE KHACHANG
ADD Email VARCHAR (100);

ALTER TABLE KHACHANG
ALTER COLUMN Email VARCHAR (50);

ALTER TABLE KHACHANG 
ADD NGAYSINH DATE;

ALTER TABLE KHACHANG 
ADD CONSTRAINT NGAYSINHCHECK CHECK (NGAYSINH <= GETDATE());

TRUNCATE TABLE KHACHANG 

DROP TABLE KHACHANG